services:
  kosyncserver:
    image: ghcr.io/bryanwweber/kosyncserver:v1.2.1
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - data:/data
    environment:
      ENV: production
      LOG_LEVEL: info
      PORT: "8000"
      HOST: "0.0.0.0"
      LOOP: uvloop
      RELOAD: false
      interface: "asgi"

volumes:
  data:
