words = [
    "atuin",
    "authkey",
    "autogroup",
    "bryanwweber",
    "caddy",
    "calibre",
    "dotenv",
    "forgejo",
    "healthcheck",
    "isready",
    "karakeep",
    "kosyncserver",
    "meili",
    "namecheap",
    "nextauth",
    "openai",
    "signups",
    "tailnet",
    "tailscale",
]
