services:
  ts-forgejo:
    image: ghcr.io/tailscale/tailscale:${TAILSCALE_VERSION}
    hostname: forgejo
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:forgejo
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data-forgejo:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    restart: unless-stopped
  forgejo:
    image: codeberg.org/forgejo/forgejo:${FORGEJO_VERSION}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      # The localhost here is needed because all the containers are in the ts-forgejo network
      - FORGEJO__database__HOST=localhost:5432
      - FORGEJO__database__NAME=${FORGEJO_DB_NAME}
      - FORGEJO__database__USER=${FORGEJO_DB_USERNAME}
      - FORGEJO__database__PASSWD=${FORGEJO_DB_PASSWORD}
    restart: always
    volumes:
      - forgejo-data:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      ts-forgejo:
        condition: service_healthy
      forgejo-db:
        condition: service_healthy
    network_mode: service:ts-forgejo
  forgejo-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - "forgejo-postgres:/var/lib/postgresql/"
    network_mode: service:ts-forgejo
    environment:
      POSTGRES_USER: ${FORGEJO_DB_USERNAME}
      POSTGRES_PASSWORD: ${FORGEJO_DB_PASSWORD}
      POSTGRES_DB: ${FORGEJO_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      ts-forgejo:
        condition: service_healthy

volumes:
  forgejo-postgres:
    name: forgejo_postgres
    external: true
  forgejo-data:
    name: forgejo_data
    external: true
  tailscale-data-forgejo:
    name: tailscale-data-forgejo
