services:
  ts-karakeep:
    image: ghcr.io/tailscale/tailscale:${TAILSCALE_VERSION}
    hostname: karakeep
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:karakeep
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data-karakeep:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    restart: unless-stopped
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION}
    restart: unless-stopped
    volumes:
      - karakeep-data:/data
    network_mode: service:ts-karakeep
    environment:
      # These hosts need to be localhost because all the containers are in the ts-karakeep namespace
      MEILI_ADDR: ${MEILI_ADDR:-http://localhost:7700}
      BROWSER_WEB_URL: ${BROWSER_WEB_URL:-http://localhost:9222}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      DATA_DIR: ${DATA_DIR:-/data}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      DISABLE_SIGNUPS: ${DISABLE_SIGNUPS:-true}
      CRAWLER_FULL_PAGE_ARCHIVE: ${CRAWLER_FULL_PAGE_ARCHIVE:-true}
    depends_on:
      meilisearch:
        condition: service_started
      chrome:
        condition: service_started
      ts-karakeep:
        condition: service_healthy
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    network_mode: service:ts-karakeep
    depends_on:
      ts-karakeep:
        condition: service_healthy
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meilisearch:/meili_data
    network_mode: service:ts-karakeep
    depends_on:
      ts-karakeep:
        condition: service_healthy

volumes:
  meilisearch:
    name: karakeep_meilisearch
    external: true
  karakeep-data:
    name: karakeep_data
    external: true
  tailscale-data-karakeep:
    name: tailscale-data-karakeep
