name: Build and Push Images

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      target:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Generate build matrix
        id: generate
        uses: docker/bake-action/subaction/matrix@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6.10.0
        with:
          target: ${{ inputs.target }}
          files: docker-bake.hcl
          fields: platforms
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}},priority=700
            type=ref,event=pr,prefix=pr-,enable=true,priority=600
            type=raw,value=${{ inputs.version }},enable={{is_default_branch}},priority=800
      - name: Rename docker meta bake file
        run: |
          mv "${BAKE_FILE}" "${{ runner.temp }}/bake-meta.json"
        env:
          BAKE_FILE: ${{ steps.meta.outputs.bake-file }}
      - name: Upload meta bake definition
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: bake-meta
          path: ${{ runner.temp }}/bake-meta.json
          if-no-files-found: error
          retention-days: 1

  build-image:
    runs-on: ${{ startsWith(matrix.platforms, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    needs:
      - prepare
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download meta bake definition
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: bake-meta
          path: ${{ runner.temp }}
      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Build and push image
        id: bake
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6.10.0
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          set: |
            *.tags=${{ inputs.registry }}/${{ inputs.image_name }}
            *.platform=${{ matrix.platforms }}
            *.output=type=image,push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' && 'true' || 'false' }}
      - name: Export digest
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest=$(jq -cr ".${TARGET}.\"containerimage.digest\"" <<< "${BUILD_METADATA}")
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
        env:
          BUILD_METADATA: ${{ steps.bake.outputs.metadata }}
          TARGET: ${{ matrix.target }}
      - name: Set platform pair
        id: set-platform-pair
        run: |
          echo "platform-pair=${PLATFORM//\//-}" >> $GITHUB_OUTPUT
        env:
          PLATFORM: ${{ matrix.platforms }}
      - name: Upload digest
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: digests-${{ steps.set-platform-pair.outputs.platform-pair }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      attestations: write
      packages: write
    needs:
      - build-image
    env:
      REGISTRY: ${{ inputs.registry }}
      IMAGE_NAME: ${{ inputs.image_name }}
    steps:
      - name: Download meta bake definition
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: bake-meta
          path: ${{ runner.temp }}
      - name: Download digests
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tags from docker bake meta
        run: |
          TAGS=$(jq -cr --arg REGISTRY_IMAGE "${REGISTRY}/${IMAGE_NAME}" '.target."docker-metadata-action".tags | map(select(startswith($REGISTRY_IMAGE)) | "-t " +.) | join(" ")' ${{ runner.temp }}/bake-meta.json)
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          DOCKER_META_VERSION=$(jq -r '.target."docker-metadata-action".args.DOCKER_META_VERSION' ${{ runner.temp }}/bake-meta.json)
          echo "DOCKER_META_VERSION=$DOCKER_META_VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $TAGS $(printf "${REGISTRY}/${IMAGE_NAME}@sha256:%s " *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${REGISTRY}/${IMAGE_NAME}:${DOCKER_META_VERSION}
